package stable //nolint:testpackage // exercises unexported stable internals

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/metacubex/mihomo/adapter"
	"github.com/metacubex/mihomo/adapter/outbound"
	mihomo "github.com/metacubex/mihomo/constant"
	"github.com/rs/zerolog"

	"domains.lst/sub-preprocessor/internal/config"
)

const (
	// tidalCountryBody is what GET https://api.tidal.com/v1/country actually
	// answers from an accepted egress (captured live: HTTP 200).
	tidalCountryBody = `{"countryCode": "DE" }`
	// cloudFrontBlockedBody is what the SAME request answers from a Russian
	// egress (captured live, HTTP 403, `server: CloudFront`,
	// `x-cache: Error from cloudfront`): Tidal refuses at the CDN, so the status
	// is the only signal the gate gets.
	cloudFrontBlockedBody = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD>
<BODY><H1>403 ERROR</H1><H2>The request could not be satisfied.</H2>
Request blocked.<PRE>Generated by cloudfront (CloudFront)</PRE></BODY></HTML>`
)

// TestTidalBlockedFailsClosed pins the inverse-of-markerBlocked contract: the
// status alone decides, and only a 2xx keeps a node.
func TestTidalBlockedFailsClosed(t *testing.T) {
	t.Parallel()

	if tidalBlocked(http.StatusOK, tidalCountryBody) {
		t.Fatal("an accepted egress must not be blocked")
	}
	// The case the gate exists for: from a Russian egress Tidal never reaches
	// the API, CloudFront answers 403 with HTML. No refusal marker exists in
	// that body, so a body-based verdict would KEEP the node.
	if !tidalBlocked(http.StatusForbidden, cloudFrontBlockedBody) {
		t.Fatal("a CDN 403 is how Tidal refuses an egress; it must block")
	}
	if !tidalBlocked(http.StatusUnavailableForLegalReasons, "") {
		t.Fatal("451 must block")
	}
	// Redirects are not followed, so an interstitial never reaches the gate as
	// a 2xx.
	if !tidalBlocked(http.StatusFound, "") {
		t.Fatal("a 302 is not a passed request")
	}
	// The whole 2xx range passes whatever the body carries: a market Tidal does
	// not sell in answers normally, and an answer that is not Tidal's at all is
	// the accepted cost of judging by status alone.
	if tidalBlocked(http.StatusOK, `{"countryCode":"JP"}`) {
		t.Fatal("an unsold market answers normally and must be kept")
	}
	if tidalBlocked(http.StatusNoContent, "") {
		t.Fatal("204 is a passed request")
	}
	if tidalBlocked(http.StatusOK, "<html>captive portal</html>") {
		t.Fatal("the body is not read; a 2xx passes")
	}
}

// TestTidalURLTargetsCountryEndpoint pins the gate to the keyless geolocation
// path. The catalog endpoints (/v1/sessions, /v1/search, /v1/country/context)
// answer 401 "Missing auth parameter" for every egress, so they would report
// every node as fine.
func TestTidalURLTargetsCountryEndpoint(t *testing.T) {
	t.Parallel()

	m := &MihomoProber{geo: config.GeoBlockConfig{
		Tidal: config.TidalConfig{Endpoint: "https://api.tidal.com/"},
	}}
	if got, want := m.tidalURL(), "https://api.tidal.com/v1/country"; got != want {
		t.Fatalf("tidalURL() = %q, want %q", got, want)
	}
}

// TestTidalCheckThroughNode drives the whole through-node path — URL build,
// apiCheck fan-out, apiProbeOne dial, status classification — against a
// local server via mihomo's DIRECT outbound, so the status plumbing is proven
// to reach the verdict rather than assumed.
func TestTidalCheckThroughNode(t *testing.T) {
	t.Parallel()

	var (
		status  = http.StatusOK
		payload = tidalCountryBody
		gotPath string
	)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		w.WriteHeader(status)
		_, _ = w.Write([]byte(payload))
	}))
	defer srv.Close()

	px := adapter.NewProxy(outbound.NewDirect())
	check := func() APIOutcome {
		t.Helper()
		m := &MihomoProber{logger: zerolog.Nop(), geo: config.GeoBlockConfig{
			Tidal: config.TidalConfig{
				Endpoint:    srv.URL,
				Timeout:     5 * time.Second,
				Concurrency: 1,
			},
		}}
		o, ok := m.TidalCheck(context.Background(), []mihomo.Proxy{px})[px.Name()]
		if !ok {
			t.Fatalf("no outcome for %q", px.Name())
		}
		return o
	}

	if o := check(); !o.Reachable || o.Blocked {
		t.Fatalf("an answered probe must be kept: %+v", o)
	}
	if gotPath != "/v1/country" {
		t.Fatalf("probed path = %q, want /v1/country", gotPath)
	}

	// The RU shape: a CDN refusal reaches the node as a response, so Reachable
	// stays true — only the status tells the gate this egress is refused.
	status, payload = http.StatusForbidden, cloudFrontBlockedBody
	if o := check(); !o.Reachable || !o.Blocked {
		t.Fatalf("CDN 403 must classify as blocked, not as an unclassifiable keep: %+v", o)
	}
}
