log:
  level: info
server:
  listen: :8080
geofeed:
  refresh_interval: 24h
  sources:
    - url: https://github.com/ipanalytics/GeoFeed-Harvester/releases/latest/download/geofeed.csv.gz
      type: gzip
    - url: https://raw.githubusercontent.com/Simonadascalu/Freedomtech-Geofeed/refs/heads/main/Freedomtech%20solutions%20-%20ALL
      type: raw
resolver:
  timeout: 5s
  cache_ttl: 30m
  cache_negative_ttl: 10m
workflow:
  stages:
    - asn
    # - geofeed
asn:
  deny_patterns:
    - "(?i)VDSINA"
    - "(?i)HOSTOFF"
    - "(?i)ServHost"
    - "(?i)TAKEHOST-AS"
    - "(?i)CHERRYSERVERS1-AS"
    - "(?i)DINSERVGRO-NET"
    - "(?i)AS56971"
    - "(?i)EXPRESSHOST"
    - "(?i)BV-EU-AS"
    - "(?i)PUSHPKT"
    - "(?i)VPSPay-ASN"
    - "(?i)TWC-EU"
    - "(?i)RETN-LV"
    - "(?i)ETERNITY-AS"
    - "(?i)DEDIK-IO"
    - "(?i)nodehost-as"
    - "(?i)GreatFlower"
    - "(?i)lain"
    - "(?i)QWINS-LTD"
    - "(?i)HOSTKEY-AS"
    - "(?i)PLYM-AS"
    - "(?i)GIR-AS"
    - "(?i)CHERRYSERVERS5-AS"
    - "(?i)MHost-AS"
    - "(?i)THE"
    - "(?i)SELECTEL-MSK"
  timeout: 5s
groups:
  nato:
    - "AL"
    - "BE"
    - "BG"
    - "CA"
    - "HR"
    - "CZ"
    - "DK"
    - "EE"
    - "FI"
    - "FR"
    - "DE"
    - "GR"
    - "HU"
    - "IS"
    - "IT"
    - "LV"
    - "LT"
    - "LU"
    - "ME"
    - "NL"
    - "MK"
    - "NO"
    - "PL"
    - "PT"
    - "RO"
    - "SK"
    - "SI"
    - "ES"
    - "SE"
    - "TR"
    - "GB"
    - "US"
  geo_blocked:
    - "RU"
    - "IR"
    - "SY"
    - "KP"
    - "CU"
    - "CN"
    - "BY"
subscriptions:
  interval: 30m
  exclude_groups:
    - geo_blocked
  sources:
    - name: mifa
      url: https://mifa.world/vless
    - name: aetris
      url: https://raw.githubusercontent.com/flaafix/AetrisVPN-black-list/refs/heads/main/configs.txt
    - name: purple
      url: https://hub.mos.ru/panosenk/sukasubs/-/raw/main/purple.txt
    - name: mehrtat
      url: https://raw.githubusercontent.com/mehrtat/vless-collector/main/vless.txt
    - name: mhditaheri
      url: https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/vless
    - name: iboxz
      url: https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/vless
    - name: ebrasha
      url: https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/main/V2Ray-Config-By-EbraSha.txt
    - name: bahemmat
      url: https://raw.githubusercontent.com/MohammadBahemmat/V2ray-Collector/main/all_servers.txt
