log:
  level: info
server:
  listen: :8080
geofeed:
  refresh_interval: 24h
  sources:
    - url: https://github.com/ipanalytics/GeoFeed-Harvester/releases/latest/download/geofeed.csv.gz
      type: gzip
    - url: https://raw.githubusercontent.com/Simonadascalu/Freedomtech-Geofeed/refs/heads/main/Freedomtech%20solutions%20-%20ALL
      type: raw
resolver:
  timeout: 5s
  cache_ttl: 1h
  cache_negative_ttl: 10m
workflow:
  stages:
    - asn
    # - geofeed
asn:
  deny_patterns:
    - "(?i)VDSINA"
    - "(?i)HOSTOFF"
    - "(?i)ServHost"
    - "(?i)TAKEHOST-AS"
    - "(?i)CHERRYSERVERS1-AS"
    - "(?i)DINSERVGRO-NET"
    - "(?i)AS56971"
    - "(?i)EXPRESSHOST"
    - "(?i)BV-EU-AS"
    - "(?i)PUSHPKT"
    - "(?i)VPSPay-ASN"
    - "(?i)TWC-EU"
    - "(?i)RETN-LV"
    - "(?i)ETERNITY-AS"
    - "(?i)DEDIK-IO"
    - "(?i)nodehost-as"
    - "(?i)GreatFlower"
    - "(?i)lain"
    - "(?i)QWINS-LTD"
    - "(?i)HOSTKEY-AS"
    - "(?i)PLYM-AS"
    - "(?i)GIR-AS"
    - "(?i)CHERRYSERVERS5-AS"
    - "(?i)MHost-AS"
    - "(?i)THE"
    - "(?i)SELECTEL-MSK"
  timeout: 5s
groups:
  nato:
    - "AL"
    - "BE"
    - "BG"
    - "CA"
    - "HR"
    - "CZ"
    - "DK"
    - "EE"
    - "FI"
    - "FR"
    - "DE"
    - "GR"
    - "HU"
    - "IS"
    - "IT"
    - "LV"
    - "LT"
    - "LU"
    - "ME"
    - "NL"
    - "MK"
    - "NO"
    - "PL"
    - "PT"
    - "RO"
    - "SK"
    - "SI"
    - "ES"
    - "SE"
    - "TR"
    - "GB"
    - "US"
  geo_blocked:
    - "RU"
    - "IR"
    - "SY"
    - "KP"
    - "CU"
    - "CN"
    - "BY"
subscriptions:
  interval: 30m
  exclude_groups:
    - geo_blocked
  sources:
    - name: mifa
      url: https://mifa.world/vless
    - name: aetris
      url: https://raw.githubusercontent.com/flaafix/AetrisVPN-black-list/refs/heads/main/configs.txt
    - name: purple
      url: https://hub.mos.ru/panosenk/sukasubs/-/raw/main/purple.txt
    - name: mehrtat
      url: https://raw.githubusercontent.com/mehrtat/vless-collector/main/vless.txt
    - name: mhditaheri
      url: https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/vless
    - name: iboxz
      url: https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/vless
    - name: ebrasha
      url: https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/main/V2Ray-Config-By-EbraSha.txt
    - name: bahemmat
      url: https://raw.githubusercontent.com/MohammadBahemmat/V2ray-Collector/main/all_servers.txt
    - name: bijandi
      url: https://raw.githubusercontent.com/amir-reza-bijandi/v2ray-configs/main/configs.txt
    - name: 3inker
      url: https://raw.githubusercontent.com/3inker/v2ray-subscription/main/subs/all_not_ru.txt
    - name: huangyurong
      url: https://raw.githubusercontent.com/HuangYurong123/p-configs/main/Splitted-By-Protocol/vless.txt
    - name: rabbitson
      url: https://raw.githubusercontent.com/MrRabbitson/RabbitProxyZ-proxy-list/refs/heads/main/lite.txt
    - name: formatorcn
      url: https://raw.githubusercontent.com/formatorcn/daily-v2ray-sub/main/sub.txt
    - name: slxkware
      url: https://raw.githubusercontent.com/slxkware/Vless-list/main/White%20Vless.txt
    - name: zxcursed
      url: https://raw.githubusercontent.com/zxcursedzxc0721/vless-subscriptions/main/all/vless.txt
    - name: fifthidea
      url: https://raw.githubusercontent.com/fifthidea/sub/main/sub/sub-full-plaintxt.txt
    - name: ninjanexus
      url: https://raw.githubusercontent.com/ninjastrikers/nexus-nodes/main/configs/vless.txt
    - name: darmioniks
      url: https://raw.githubusercontent.com/Darmioniks/proxy-and-vless-collector/main/vless_filtered.txt
    - name: theavel
      url: https://raw.githubusercontent.com/theavel/free-vless-proxy/main/all.txt
    - name: yafeisun
      url: https://raw.githubusercontent.com/yafeisun/v2raynode/refs/heads/main/result/karing.txt
    - name: jagger
      url: https://raw.githubusercontent.com/jagger235711/V2rayCollector/main/results/vless.txt
    - name: wlunlocker
      url: https://raw.githubusercontent.com/wlunlocker/vpn-configs/main/blacklist_vpn1.txt
    - name: ishalumi
      url: https://raw.githubusercontent.com/ishalumi/proxy-node-collector/main/output/nodes.txt
    - name: yuanxiawan
      url: https://raw.githubusercontent.com/yuanxiawan/freevless/main/results/valid_vless_configs.txt
    - name: vova
      url: https://raw.githubusercontent.com/VovaplusEXP/p-configs/main/Splitted-By-Protocol-Secure/vless.txt
    - name: avia
      url: https://raw.githubusercontent.com/aviamastersgh/vpn-free-russia/main/verified_configs.txt
    - name: prince
      url: https://raw.githubusercontent.com/PrinceVSFX/Adapt-Configs/main/Configs/White_list.txt
    - name: qjlxg
      url: https://raw.githubusercontent.com/qjlxg/eastmoney/main/all_nodes.txt
    - name: niqonopin
      url: https://raw.githubusercontent.com/niq0n0pin/v2rayfree-nice-tracker/main/backup/nodes.txt
    - name: wind7077
      url: https://raw.githubusercontent.com/Wind7077/vl-checker/main/output/proxies.txt
    - name: tepo80
      url: https://raw.githubusercontent.com/tepo80/tepo80/main/vmess.txt
