subscriptions:
  sources:
    - name: aetris
      url: https://raw.githubusercontent.com/flaafix/AetrisVPN-black-list/refs/heads/main/configs.txt
    - name: purple
      url: https://hub.mos.ru/panosenk/sukasubs/-/raw/main/purple.txt
    - name: mehrtat
      url: https://raw.githubusercontent.com/mehrtat/vless-collector/main/vless.txt
    - name: mhditaheri
      url: https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/vless
    - name: iboxz
      url: https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/vless
    - name: bahemmat
      url: https://raw.githubusercontent.com/MohammadBahemmat/V2ray-Collector/main/all_servers.txt
    - name: bijandi
      url: https://raw.githubusercontent.com/amir-reza-bijandi/v2ray-configs/main/configs.txt
    - name: 3inker
      url: https://raw.githubusercontent.com/3inker/v2ray-subscription/main/subs/all_not_ru.txt
    - name: rabbitson
      url: https://raw.githubusercontent.com/MrRabbitson/RabbitProxyZ-proxy-list/refs/heads/main/lite.txt
    - name: zxcursed
      url: https://raw.githubusercontent.com/zxcursedzxc0721/vless-subscriptions/main/all/vless.txt
    - name: fifthidea
      url: https://raw.githubusercontent.com/fifthidea/sub/main/sub/sub-full-plaintxt.txt
    - name: ninjanexus
      url: https://raw.githubusercontent.com/ninjastrikers/nexus-nodes/main/configs/vless.txt
    - name: darmioniks
      url: https://raw.githubusercontent.com/Darmioniks/proxy-and-vless-collector/main/vless_filtered.txt
    - name: theavel
      url: https://raw.githubusercontent.com/theavel/free-vless-proxy/main/all.txt
    - name: yafeisun
      url: https://raw.githubusercontent.com/yafeisun/v2raynode/refs/heads/main/result/karing.txt
    - name: ishalumi
      url: https://raw.githubusercontent.com/ishalumi/proxy-node-collector/main/output/nodes.txt
    - name: yuanxiawan
      url: https://raw.githubusercontent.com/yuanxiawan/freevless/main/results/valid_vless_configs.txt
    - name: vova
      url: https://raw.githubusercontent.com/VovaplusEXP/p-configs/main/Splitted-By-Protocol-Secure/vless.txt
    - name: avia
      url: https://raw.githubusercontent.com/aviamastersgh/vpn-free-russia/main/verified_configs.txt
    - name: niqonopin
      url: https://raw.githubusercontent.com/niq0n0pin/v2rayfree-nice-tracker/main/backup/nodes.txt
    - name: wind7077
      url: https://raw.githubusercontent.com/Wind7077/vl-checker/main/output/proxies.txt
    - name: tepo80
      url: https://raw.githubusercontent.com/tepo80/tepo80/main/vmess.txt
    - name: etoneyaproject
      url: https://raw.githubusercontent.com/EtoNeYaProject/etoneyaproject.github.io/refs/heads/main/1
    - name: bywarm-merged
      url: https://gitverse.ru/api/repos/bywarm/rser/raw/branch/master/merged.txt
    - name: goida
      url: https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/26.txt
    - name: igareck-white
      url: https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt
    - name: prominbro
      url: https://raw.githubusercontent.com/prominbro/sub/refs/heads/main/212.txt
    - name: obhodwl
      url: https://raw.githubusercontent.com/tankist939-afk/Obhod-WL/refs/heads/main/Obhod%20WL
    - name: reality
      url: https://gitflic.ru/project/sigil/my-new-cool-project/blob/raw?file=whitelist
    - name: genlib
      url: https://raw.githubusercontent.com/gergew452/Generation-Liberty/refs/heads/main/githubmirror/best.txt
    - name: whitelist-sanuyyq
      url: https://raw.githubusercontent.com/Sanuyyq/sub-storage1/refs/heads/main/bs.txt
    - name: shatak
      url: https://raw.githubusercontent.com/ShatakVPN/ConfigForge-V2Ray/main/configs/ru/vless.txt
    - name: rostunnel-gen
      url: https://subrostunnel.vercel.app/gen.txt
    - name: rostunnel-mega
      url: https://rostunnel.vercel.app/mega.txt
    - name: abikus
      url: https://cdn.jsdelivr.net/gh/AbikusSudo/RussiaVPN@main/docs/index.html
    - name: flat447
      url: https://github.com/FLAT447/v2ray-lists/raw/refs/heads/main/BLACK_FULL.txt
    - name: fastnodes-se
      url: https://raw.githubusercontent.com/rtwo2/FastNodes/main/sub/countries/SE.txt
    - name: fastnodes-fi
      url: https://raw.githubusercontent.com/rtwo2/FastNodes/main/sub/countries/FI.txt
    - name: vify
      url: https://raw.githubusercontent.com/Mr-Meshky/vify/main/configs/alive.txt
    - name: bocchi2b
      url: https://links.bocchi2b.top/clash
    - name: zhuhaiuk
      url: https://raw.githubusercontent.com/zhuhaiuk/free-nodes/main/nodes.txt
    - name: kasesm
      url: https://raw.githubusercontent.com/kasesm/Free-Config/main/all_raw.txt
    - name: kernyx
      url: https://gitverse.ru/api/repos/Kernyx/notes/raw/branch/master/sub.txt
    - name: apelsintel
      url: https://gitverse.ru/api/repos/bikinitw22/apelsintel/raw/branch/main/alive_full.txt
    - name: vdevel26
      url: https://gitverse.ru/api/repos/vdevel/proxy/raw/branch/main/26.txt
    - name: gidro-white
      url: https://gitverse.ru/api/repos/gidro/white/raw/branch/master/subscription.txt
    - name: fnoide-keys
      url: https://gitverse.ru/api/repos/Fnoide/Keys/raw/branch/main/processed_keys.txt
    - name: ultav-white
      url: https://gitverse.ru/api/repos/volondses/ultav/raw/branch/master/UltavWhite.txt
    - name: bazz1024-mirror
      url: https://gitverse.ru/api/repos/Bazz1024/vpn-configs-mirror/raw/branch/main/rkn_white_list
    - name: rjsxrd-bypass
      url: https://raw.githubusercontent.com/whoahaow/rjsxrd/refs/heads/main/githubmirror/bypass/bypass-all.txt
    - name: ruvipien-goida
      url: https://gitverse.ru/api/repos/RUVIPIEN/russian-white-bolt/raw/branch/master/VPNMIRRORS/vless/GOIDA_VLESS_1__AvenCores_.txt
    - name: emillynn-au1rxx
      url: https://gitverse.ru/api/repos/Emillynn/sub-configs-mirror/raw/branch/master/au1rxx-v2ray.txt
    - name: emillynn-goida24
      url: https://gitverse.ru/api/repos/Emillynn/sub-configs-mirror/raw/branch/master/goida-24.txt
    - name: linspisok-all
      url: https://hub.mos.ru/LinSpisokObhod/LInSpisokObhod/-/raw/main/sub/ALL.txt
    - name: ruwbl-rostun
      url: https://gitverse.ru/api/repos/ru-wbl/wl/raw/branch/master/RosTun/utf-8_wl.txt
    - name: xalador
      url: https://gitverse.ru/api/repos/Xalador/AutoConfig/raw/branch/master/output.txt
    - name: ruwbl-outline
      url: https://gitverse.ru/api/repos/ru-wbl/wl/raw/branch/master/OutlineVPN/OutlineVPN.txt
    - name: ayub-mobile
      url: https://gitverse.ru/api/repos/Ayub/vpn-configs-for-russia/raw/branch/main/BLACK_VLESS_RUS_mobile.txt
    - name: ruwbl-zieng2
      url: https://gitverse.ru/api/repos/ru-wbl/wl/raw/branch/master/Zieng2/Zieng2_vless_lite.txt
    - name: ayub-rus
      url: https://gitverse.ru/api/repos/Ayub/vpn-configs-for-russia/raw/branch/main/BLACK_VLESS_RUS.txt
    - name: ayub-ss
      url: https://gitverse.ru/api/repos/Ayub/vpn-configs-for-russia/raw/branch/main/BLACK_SS%2BAll_RUS.txt
    - name: ruvipien-igareck
      url: https://gitverse.ru/api/repos/RUVIPIEN/russian-white-bolt/raw/branch/master/VPNMIRRORS/vless/VLESS_Reality_White_Lists_RU_Mobile_2__igareck_.txt
    - name: glproxy
      url: https://gitverse.ru/api/repos/glprx/glproxy/raw/branch/master/processed.txt
    - name: ayub-reality
      url: https://gitverse.ru/api/repos/Ayub/vpn-configs-for-russia/raw/branch/main/Vless-Reality-White-Lists-Rus-Mobile.txt
    - name: lonnory
      url: https://gitverse.ru/api/repos/Lonnory/VlessALL/raw/branch/master/Vpn.txt
    - name: moonlume-vless
      url: https://gitverse.ru/api/repos/moonlume/ru-whitelist/raw/branch/master/vless.txt
    - name: mirgittech-mia
      url: https://gitverse.ru/api/repos/mirgittech/mia/raw/branch/master/configs.txt
    - name: goida26-1
      url: https://gitflic.ru/project/id821859431/goida-vpn-configs26/blob/raw?file=1igarec
    - name: scalavpn
      url: https://gitflic.ru/project/scala/scalavpn-configs/blob/raw?file=sub
    - name: revotech
      url: https://gitverse.ru/api/repos/revotech.ru/xray-vless-gen/raw/branch/master/shadow.txt
