subscriptions:
  sources:
    - name: mifa
      url: https://mifa.world/vless
    - name: aetris
      url: https://raw.githubusercontent.com/flaafix/AetrisVPN-black-list/refs/heads/main/configs.txt
    - name: purple
      url: https://hub.mos.ru/panosenk/sukasubs/-/raw/main/purple.txt
    - name: mehrtat
      url: https://raw.githubusercontent.com/mehrtat/vless-collector/main/vless.txt
    - name: mhditaheri
      url: https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/vless
    - name: iboxz
      url: https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/vless
    - name: bahemmat
      url: https://raw.githubusercontent.com/MohammadBahemmat/V2ray-Collector/main/all_servers.txt
    - name: bijandi
      url: https://raw.githubusercontent.com/amir-reza-bijandi/v2ray-configs/main/configs.txt
    - name: 3inker
      url: https://raw.githubusercontent.com/3inker/v2ray-subscription/main/subs/all_not_ru.txt
    - name: rabbitson
      url: https://raw.githubusercontent.com/MrRabbitson/RabbitProxyZ-proxy-list/refs/heads/main/lite.txt
    - name: zxcursed
      url: https://raw.githubusercontent.com/zxcursedzxc0721/vless-subscriptions/main/all/vless.txt
    - name: fifthidea
      url: https://raw.githubusercontent.com/fifthidea/sub/main/sub/sub-full-plaintxt.txt
    - name: ninjanexus
      url: https://raw.githubusercontent.com/ninjastrikers/nexus-nodes/main/configs/vless.txt
    - name: darmioniks
      url: https://raw.githubusercontent.com/Darmioniks/proxy-and-vless-collector/main/vless_filtered.txt
    - name: theavel
      url: https://raw.githubusercontent.com/theavel/free-vless-proxy/main/all.txt
    - name: yafeisun
      url: https://raw.githubusercontent.com/yafeisun/v2raynode/refs/heads/main/result/karing.txt
    - name: ishalumi
      url: https://raw.githubusercontent.com/ishalumi/proxy-node-collector/main/output/nodes.txt
    - name: yuanxiawan
      url: https://raw.githubusercontent.com/yuanxiawan/freevless/main/results/valid_vless_configs.txt
    - name: vova
      url: https://raw.githubusercontent.com/VovaplusEXP/p-configs/main/Splitted-By-Protocol-Secure/vless.txt
    - name: avia
      url: https://raw.githubusercontent.com/aviamastersgh/vpn-free-russia/main/verified_configs.txt
    - name: prince
      url: https://raw.githubusercontent.com/PrinceVSFX/Adapt-Configs/main/Configs/White_list.txt
    - name: niqonopin
      url: https://raw.githubusercontent.com/niq0n0pin/v2rayfree-nice-tracker/main/backup/nodes.txt
    - name: wind7077
      url: https://raw.githubusercontent.com/Wind7077/vl-checker/main/output/proxies.txt
    - name: tepo80
      url: https://raw.githubusercontent.com/tepo80/tepo80/main/vmess.txt
    - name: etoneyaproject
      url: https://raw.githubusercontent.com/EtoNeYaProject/etoneyaproject.github.io/refs/heads/main/1
    - name: bywarm-merged
      url: https://gitverse.ru/api/repos/bywarm/rser/raw/branch/master/merged.txt
    - name: goida
      url: https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/26.txt
    - name: igareck-white
      url: https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/Vless-Reality-White-Lists-Rus-Mobile.txt
    - name: prominbro
      url: https://raw.githubusercontent.com/prominbro/sub/refs/heads/main/212.txt
    - name: obwl-wwh
      url: https://obwlsub.vercel.app/wwh
    - name: obhodwl
      url: https://raw.githubusercontent.com/tankist939-afk/Obhod-WL/refs/heads/main/Obhod%20WL
    - name: reality
      url: https://gitflic.ru/project/sigil/my-new-cool-project/blob/raw?file=whitelist
    - name: genlib
      url: https://raw.githubusercontent.com/gergew452/Generation-Liberty/refs/heads/main/githubmirror/best.txt
    - name: whitelist-sanuyyq
      url: https://raw.githubusercontent.com/Sanuyyq/sub-storage1/refs/heads/main/bs.txt
    - name: lime
      url: https://raw.githubusercontent.com/LimeHi/LimeVPNGenerator/main/Keys.txt?v=1
    - name: shatak
      url: https://raw.githubusercontent.com/ShatakVPN/ConfigForge-V2Ray/main/configs/ru/vless.txt
    - name: rostunnel-gen
      url: https://subrostunnel.vercel.app/gen.txt
    - name: rostunnel-mega
      url: https://rostunnel.vercel.app/mega.txt
    - name: abikus
      url: https://cdn.jsdelivr.net/gh/AbikusSudo/RussiaVPN@main/docs/index.html
    - name: flat447
      url: https://github.com/FLAT447/v2ray-lists/raw/refs/heads/main/BLACK_FULL.txt
    - name: fastnodes-se
      url: https://raw.githubusercontent.com/rtwo2/FastNodes/main/sub/countries/SE.txt
    - name: fastnodes-fi
      url: https://raw.githubusercontent.com/rtwo2/FastNodes/main/sub/countries/FI.txt
    - name: vify
      url: https://raw.githubusercontent.com/Mr-Meshky/vify/main/configs/alive.txt
    - name: bocchi2b
      url: https://links.bocchi2b.top/clash
    - name: zhuhaiuk
      url: https://raw.githubusercontent.com/zhuhaiuk/free-nodes/main/nodes.txt
    - name: kasesm
      url: https://raw.githubusercontent.com/kasesm/Free-Config/main/all_raw.txt
    - name: wepogp-1
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=9Uysah7/fNwcH4ZJtls6A4Z7UCZ9hyL1hepLRS1kavYU555xTTqq4nGazHwhIJ%2BAWCwES/fmUfcpC1f3KXbVhsynIWUHbjEFRm37H2t%2BrNItwjcbN8j6D4arQKoCCb3/2nLMsLAYo29QGnH4ei51yctLBhubqY8eUgubEq9U4zc%3D"
    - name: wepogp-2
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=LZgRo3fjD0PYxY9QdngXXYeRxmLsF4wnd3aE2%2BUfUzEDDH%2Bv96RMWMddfOY3OZlpYS%2BFl4RWMUY5lNg2SQtAkIzkRszXQrXhBCg4G0XmaVl1uAqG6VBPW9J0fIkfFkaG"
    - name: wepogp-3
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=LZgRo3fjD0PYxY9QdngXXYeRxmLsF4wnd3aE2%2BUfUzHO030rad6OUjzSSzu7E%2Bdq2STODGsJm/vTgPgdOVSmkIv4AOPXL4ulc0RnalezhML3GVkaTSbSmBf4YufYGRFq"
    - name: wepogp-4
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=TT9IrxOfhgJyEk0MCOdGYXwx6vwM%2Bi30GcZkAeCHYhCGDHEqZJJKYTE61E1nPyGNDm274BT9fzc8PEKr3Xj5hC1A3Xt7p%2BCmcI7SXDA86nr0uvOInbPurA3heJf4d%2BFhkAjTFkQJ/rfGYEDZVuFVC4BxV/diP0/xn0qHNU8PNC0qAafArQuNc0ZT5noIrVKn"
    - name: wepogp-5
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=ncTwh6gLb370N1FwGTSe9FPwZxM8uFWYJOSPWbo7QreJUCFVW84ZPq8/sdNUKlnXb21ftuvaaLnJUEqjhb63S1eK%2BVQuYI2%2Boj1TEADb/m/1tga9qF7onHhZrxFlRZBRcKH8ysDzfLmWd9IhowLLEWwAlL5TAOx7I0E3Bb5FircknxatdMjNeDT6Sj7bBqyFx7zTmZoVEtL9IiRInsh3Kw%3D%3D"
    - name: hiddify-json-1
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=2LLLFsrUEbu/f%2BATtUSE8Zl9ewgkE6CpWA6gdeM73E/6duxh2/ig3XZO47aipHllGIh%2BhyIKFxQVDxUljsOREg%3D%3D"
    - name: hiddify-json-2
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=G67mXxr1jIi1m/fQdPf/7NETdAvA9itWaCgz9T/8tBOMBSJsMyKyzKkIfSmdsPPBg38p1VG/WbUmhm2ztF7zok9vNOCJz11FP78AwBbJARs%3D"
    - name: hiddify-json-3
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=fNa6u0Pjn75vEyCYHnDCWkojZrck%2Bge3BYHwx6EB0ZkTAzw0qSrIx1wpkYTwz1cbrEjmcBej08msB/D9qP3AF/BjNDvlGSg5M%2BNBwuIBg8c%3D"
    - name: hiddify-json-4
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=fNa6u0Pjn75vEyCYHnDCWkojZrck%2Bge3BYHwx6EB0ZmvNbVys0cNqfeZdFW6Vo1J%2BeI7ddjyqGx14l2i%2BGbxaHT8MVbsi1uqDgIASAKN3Zs%3D"
    - name: hiddify-json-5
      url: "https://is.wepogp.gay/bypass-hwid-lock-3z5O6BFAaJQzGlamvtSo?payload=rFrJwgET4BVCUTFJTuhto8Fj4ZmEfgMOIlyPWhz/TPBL8B49xLa2XApmU0KzhBpqClwcuNSUMLUFHZyCRWmuZg%3D%3D"
